### ISSUE TITLE
DiffEditor does not highlight diffs

### ISSUE THREAD

**Issue by rahulthewall** [securingsincity/react-ace#1962]
# Problem
I am trying to use the DiffEditor, but it does not highlight the differences in the two texts. 

## Sample code to reproduce your issue
The code has been reproduced here: https://replit.com/@rahulthewall/WingedTanMultiprocessing?v=1

**Comment by wxupjack** [comment]
add `:global` before the `.codeMarker {}` to avoid CSS modules localize the class name. [Source from this repo's disscussion](https://github.com/securingsincity/react-ace/discussions/751#discussioncomment-182855) 

```css
:global .codeMarker {
    background-color: #ffff99 ;
    position: absolute ;
    z-index: 20;
}
```
