### ISSUE TITLE
Marker highlight the whole line even startCol and endCol defined to limit the columns

### ISSUE THREAD

**Issue by prasadlvi** [securingsincity/react-ace#541]
I use the following code to highlight a text range. 

```javascript
    let markers = [];
    markers.push({startRow: 6, startCol: 5, endRow: 7, endCol: 6, className: 'replacement_marker', type: 'text' });
```

React render() :

```react
        return (
            <div>
                <AceEditor
                    mode="java"
                    theme="github"you 
                    name="UNIQUE_ID_OF_DIV"
                    value={this.state.value}
                    markers={markers}
                />
            </div>
        );
```

```css
    .replacement_marker {
       position: absolute;
       background-color: #FFFF00;
    }
```

With this code, editor highlights the whole line 6 and 7 without limiting the highlight to column 5 - 6. 

[![enter image description here][1]][1]

Can you confirm whether this is a bug in React-ace or a issue in the way I used it? Thank you.

  [1]: https://i.stack.imgur.com/4652I.png

**Comment by prasadlvi** [comment]
In my case, this was due to a bad custom CSS. Not a bug in react-ace.

```css
.ace_marker-layer {
  > div:not(.ace_selection){
    width: 100% !important;
    border-radius: unset !important;
    left: 0 !important;
  }
}
```
